#!/usr/bin/env bash
#
# Render every example page in dark and light mode and refresh
# docs/SCREENSHOTS.md. Used by .github/workflows/screenshots.yml and
# runnable locally:
#
#   scripts/capture-screenshots.sh
#
# Requires Python 3 and either a `playwright` binary on PATH or npx.
# Set PLAYWRIGHT_VERSION to pin the CLI version used via npx.

set -euo pipefail

PORT="${PORT:-8137}"
HOST="127.0.0.1"
OUT_DIR="docs/screenshots"
MD_FILE="docs/SCREENSHOTS.md"
VIEWPORT="1440,900"
MOBILE_VIEWPORT="390,844"
PLAYWRIGHT_VERSION="${PLAYWRIGHT_VERSION:-1.53.0}"

cd "$(dirname "$0")/.."

if command -v playwright >/dev/null 2>&1; then
  PW=(playwright)
else
  PW=(npx --yes "playwright@${PLAYWRIGHT_VERSION}")
fi

mkdir -p "$OUT_DIR"

python3 -m http.server "$PORT" --bind "$HOST" >/dev/null 2>&1 &
SERVER_PID=$!
trap 'kill "$SERVER_PID" 2>/dev/null || true' EXIT

for _ in $(seq 1 50); do
  if curl -fs "http://$HOST:$PORT/examples/" >/dev/null 2>&1; then break; fi
  sleep 0.2
done
curl -fs "http://$HOST:$PORT/examples/" >/dev/null   # fail loudly if never up

shot() {
  # shot <name> <page> <mode> <full|viewport> [viewport-size]
  local name="$1" page="$2" mode="$3" kind="$4" size="${5:-$VIEWPORT}"
  local out="$OUT_DIR/$name-$mode.png"
  local args=(
    screenshot
    --browser=chromium
    "--color-scheme=$mode"
    "--viewport-size=$size"
    --wait-for-timeout=700
  )
  [ "$kind" = "full" ] && args+=(--full-page)
  args+=("http://$HOST:$PORT/examples/$page" "$out")
  echo "→ $out"
  "${PW[@]}" "${args[@]}" >/dev/null
}

for mode in dark light; do
  shot overview index.html "$mode" full
  shot components components.html "$mode" full
  shot settings settings.html "$mode" full
  shot workspace workspace.html "$mode" viewport
  shot auth auth.html "$mode" viewport
done
shot workspace-mobile workspace.html dark viewport "$MOBILE_VIEWPORT"

SOURCE_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo 'local checkout')"
GENERATED_AT="$(date -u '+%Y-%m-%d %H:%M UTC')"

row() {
  # row <label> <name>
  printf '| %s | ![%s — dark](screenshots/%s-dark.png) | ![%s — light](screenshots/%s-light.png) |\n' \
    "$1" "$1" "$2" "$1" "$2"
}

{
  cat <<HEADER
# Screenshots

Generated by the [Screenshots workflow](../.github/workflows/screenshots.yml)
from the pages in \`examples/\` at commit \`$SOURCE_SHA\` ($GENERATED_AT).
Do not edit by hand — the workflow rewrites this file whenever the theme or
the examples change on \`main\`.

| Page | Dark | Light |
| --- | --- | --- |
HEADER
  row Overview overview
  row "Component catalog" components
  row Settings settings
  row "Workspace shell" workspace
  row Authentication auth
  cat <<FOOTER

## Responsive

The workspace shell at a 390px viewport, dark mode:

![Workspace shell — mobile dark](screenshots/workspace-mobile-dark.png)
FOOTER
} > "$MD_FILE"

echo "✓ screenshots written to $OUT_DIR and $MD_FILE refreshed"
